import {
  Box,
  Button,
  Img,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Text,
  useDisclosure,
} from "@chakra-ui/react";

function BasicUsage() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  return (
    <>
      <Button
        w="100%"
        py="24px"
        colorScheme="#363B52"
        bg="#363B52"
        width="100%"
        color="#4E5370"
        fontSize="18px"
        height="70px"
        size="lg"
        mr="2"
        onClick={onOpen}
      >
        Add Liquidity
      </Button>

      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent bg={"#161A2D"} maxWidth="528px" w="100%">
          <ModalHeader
            color={"white"}
            fontSize="18px"
            lineHeight={"27px"}
            fontWeight="600"
          >
            Add Liquiditys
          </ModalHeader>
          <ModalCloseButton
            color="#7B7B7B"
            p="2px"
            border="2px solid #7B7B7B"
            borderRadius="50%"
            top="16px"
            right="26px"
          />
          <ModalBody>
            <Box>
              <Box
                display={"flex"}
                justifyContent="space-between"
                alignItems={"center"}
              >
                <Box
                  display={"flex"}
                  justifyContent="flex-start"
                  alignItems={"flex-start"}
                  gap="11px"
                >
                  <Img src="/Teh.png" />
                  <Text
                    as={"span"}
                    color="white"
                    fontSize={"20px"}
                    lineHeight="30px"
                    fontWeight={"600"}
                  >
                    ETH / USDT
                  </Text>
                </Box>
                <Box
                  display={"flex"}
                  justifyContent="flex-start"
                  alignItems={"center"}
                  gap="11px"
                >
                  <Img src="/greencircle.svg" />
                  <Text
                    as="span"
                    color="white"
                    fontSize={"15px"}
                    lineHeight="22x"
                    fontWeight={"600"}
                  >
                    In range
                  </Text>
                </Box>
              </Box>
              <Box
                bg={"#323756"}
                borderRadius="4px"
                p="24px"
                mt="21px"
                mb={"12px"}
              >
                <Box
                  display={"flex"}
                  justifyContent="space-between"
                  alignItems={"center"}
                >
                  <Box
                    display={"flex"}
                    justifyContent="flex-start"
                    alignItems={"flex-start"}
                    gap="11px"
                  >
                    <Img src="/ETH.svg" />
                    <Text
                      as={"span"}
                      color="white"
                      fontSize={"20px"}
                      lineHeight="30px"
                      fontWeight={"600"}
                    >
                      ETH / USDT
                    </Text>
                  </Box>
                  <Box
                    display={"flex"}
                    justifyContent="flex-start"
                    alignItems={"center"}
                    gap="11px"
                  >
                    <Text
                      as="span"
                      color="white"
                      fontSize={"15px"}
                      lineHeight="22x"
                      fontWeight={"600"}
                    >
                      0.02424
                    </Text>
                  </Box>
                </Box>
                <Box
                  display={"flex"}
                  justifyContent="space-between"
                  alignItems={"center"}
                  py={"13px"}
                  borderBottom="1px solid #55575C"
                >
                  <Box
                    display={"flex"}
                    justifyContent="flex-start"
                    alignItems={"flex-start"}
                    gap="11px"
                  >
                    <Img src="/Teh.svg" />
                    <Text
                      as={"span"}
                      color="white"
                      fontSize={"20px"}
                      lineHeight="30px"
                      fontWeight={"600"}
                    >
                      ETH / USDT
                    </Text>
                  </Box>
                  <Box
                    display={"flex"}
                    justifyContent="flex-start"
                    alignItems={"center"}
                    gap="11px"
                  >
                    <Text
                      as="span"
                      color="white"
                      fontSize={"15px"}
                      lineHeight="22x"
                      fontWeight={"600"}
                    >
                      49.99
                    </Text>
                  </Box>
                </Box>
                <Box
                  display={"flex"}
                  justifyContent="space-between"
                  alignItems={"center"}
                  pt={"13px"}
                >
                  <Box
                    display={"flex"}
                    justifyContent="flex-start"
                    alignItems={"flex-start"}
                    gap="11px"
                  >
                    <Text
                      as={"span"}
                      color="white"
                      fontSize={"20px"}
                      lineHeight="30px"
                      fontWeight={"600"}
                    >
                      Fee Tier
                    </Text>
                  </Box>
                  <Box
                    display={"flex"}
                    justifyContent="flex-start"
                    alignItems={"center"}
                    gap="11px"
                  >
                    <Text
                      as="span"
                      color="white"
                      fontSize={"15px"}
                      lineHeight="22x"
                      fontWeight={"600"}
                    >
                      0.3%
                    </Text>
                  </Box>
                </Box>
              </Box>
              <Box pt={"16px"} pb="13px">
                <Box
                  display={"flex"}
                  justifyContent="space-between"
                  alignItems={"center"}
                >
                  <Box>
                    <Text
                      color={"white"}
                      fontSize="16px"
                      lineHeight={"24px"}
                      fontWeight="500"
                      fontFamily={"poppins"}
                    >
                      Selected Range
                    </Text>
                  </Box>
                  <Box
                    bg={"#252B4B"}
                    borderRadius="4px"
                    p={"4px"}
                    display="flex"
                    gap={"15px"}
                  >
                    <Box>
                      <Text
                        fontSize={"14px"}
                        lineHeight="21px"
                        letterSpacing={"-0.011em"}
                        color="white"
                        bg={"#36407D"}
                        borderRadius="2px"
                        fontFamily={"poppins"}
                        py={"4px"}
                        px="18px"
                        fontWeight={"600"}
                      >
                        ETH
                      </Text>
                    </Box>
                    <Box>
                      <Text
                        fontSize={"14px"}
                        lineHeight="21px"
                        letterSpacing={"-0.011em"}
                        color="white"
                        fontFamily={"poppins"}
                        py={"4px"}
                        px="10px"
                        fontWeight={"600"}
                      >
                        USDT
                      </Text>
                    </Box>
                  </Box>
                </Box>
              </Box>
              <Box
                display={"flex"}
                gap="20px"
                w={"100%"}
                flexDirection={{ base: "column", md: "row" }}
              >
                <Box bg={"#323756"} borderRadius="4px" p={"13px"}>
                  <Text
                    as={"p"}
                    fontSize="15px"
                    lineHeight={"24px"}
                    fontFamily="poppins"
                    color={"#A8A9B5"}
                    fontWeight="700"
                    textAlign="center"
                  >
                    Min Price
                  </Text>
                  <Text
                    as={"h2"}
                    fontSize="24px"
                    lineHeight={"33px"}
                    fontWeight="700"
                    fontFamily={"poppins"}
                    color="white"
                    textAlign="center"
                  >
                    820.63
                  </Text>
                  <Text
                    as={"p"}
                    fontSize="15px"
                    lineHeight={"24px"}
                    fontFamily="poppins"
                    color={"#A8A9B5"}
                    fontWeight="700"
                    textAlign="center"
                  >
                    USDT per ETH
                  </Text>
                  <Text
                    as={"p"}
                    fontSize="14px"
                    lineHeight={"18px"}
                    fontFamily="poppins"
                    color="#7A7B88"
                    fontWeight="400"
                    letterSpacing={"-0.011em"}
                    textAlign="center"
                  >
                    Your position will be 100% composed of ETH at this price
                  </Text>
                </Box>
                <Box bg={"#323756"} borderRadius="4px" p={"13px"}>
                  <Text
                    as={"p"}
                    fontSize="15px"
                    lineHeight={"24px"}
                    fontFamily="poppins"
                    color={"#A8A9B5"}
                    fontWeight="700"
                    textAlign="center"
                  >
                    Min Price
                  </Text>
                  <Text
                    as={"h2"}
                    fontSize="24px"
                    lineHeight={"33px"}
                    fontWeight="700"
                    fontFamily={"poppins"}
                    color="white"
                    textAlign="center"
                  >
                    820.63
                  </Text>
                  <Text
                    as={"p"}
                    fontSize="15px"
                    lineHeight={"24px"}
                    fontFamily="poppins"
                    color={"#A8A9B5"}
                    fontWeight="700"
                    textAlign="center"
                  >
                    USDT per ETH
                  </Text>
                  <Text
                    as={"p"}
                    fontSize="14px"
                    lineHeight={"18px"}
                    fontFamily="poppins"
                    color="#7A7B88"
                    fontWeight="400"
                    letterSpacing={"-0.011em"}
                    textAlign="center"
                  >
                    Your position will be 100% composed of ETH at this price
                  </Text>
                </Box>
              </Box>
              <Box bg={"#323756"} borderRadius="4px" p={"13px"} my="24px">
                <Text
                  as={"p"}
                  fontSize="15px"
                  lineHeight={"24px"}
                  fontFamily="poppins"
                  color={"#A8A9B5"}
                  fontWeight="700"
                  textAlign="center"
                >
                  Current Price
                </Text>
                <Text
                  as={"h2"}
                  fontSize="24px"
                  lineHeight={"33px"}
                  fontWeight="700"
                  fontFamily={"poppins"}
                  color="white"
                  textAlign="center"
                >
                  1637.4
                </Text>
                <Text
                  as={"p"}
                  fontSize="15px"
                  lineHeight={"24px"}
                  fontFamily="poppins"
                  color={"#A8A9B5"}
                  fontWeight="700"
                  textAlign="center"
                >
                  USDT per ETH
                </Text>
              </Box>
            </Box>
          </ModalBody>

          <ModalFooter>
            <Button
              colorScheme="#3B41D8"
              mr={3}
              borderRadius="3px"
              onClick={onClose}
              bg="#3B41D8"
              color={"white"}
              p="24px"
              w={"100%"}
            >
              Close
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
}
export default BasicUsage;
